/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './arena.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../auth/auth.service';
import * as import9 from '../game-list/game-list.services';
import * as import10 from '../socketHanding/socket.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from './arena-header.component';
import * as import16 from '../opponent-find/opponent-find.component';
import * as import17 from '../game-list/game-list.component';
import * as import18 from './arena-header.component.ngfactory';
import * as import19 from '../opponent-find/opponent-find.component.ngfactory';
import * as import20 from '../opponent-find/opponent-find.sevices';
import * as import21 from '../game-list/game-list.component.ngfactory';
import * as import22 from '../../questions/arena-playing.component';
import * as import23 from '../../questions/arena-playing.component.ngfactory';
import * as import24 from '../../questions/questionServices/questionAnswer.service';
import * as import25 from '../../questions/questionServices/arena.service';
var renderType_ArenaComponent_Host:import0.RenderComponentType = (null as any);
class _View_ArenaComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ArenaComponent_0_4:import3.ArenaComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaComponent_Host0,renderType_ArenaComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-arena',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ArenaComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ArenaComponent_0_4 = new import3.ArenaComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.GameListServices),this.parentInjector.get(import10.SocketService));
    this._appEl_0.initComponent(this._ArenaComponent_0_4,[],compView_0);
    compView_0.create(this._ArenaComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ArenaComponent) && (0 === requestNodeIndex))) { return this._ArenaComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ArenaComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ArenaComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ArenaComponent_Host === (null as any))) { (renderType_ArenaComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_ArenaComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ArenaComponentNgFactory:import12.ComponentFactory<import3.ArenaComponent> = new import12.ComponentFactory<import3.ArenaComponent>('my-arena',viewFactory_ArenaComponent_Host0,import3.ArenaComponent);
const styles_ArenaComponent:any[] = [];
var renderType_ArenaComponent:import0.RenderComponentType = (null as any);
class _View_ArenaComponent0 extends import1.AppView<import3.ArenaComponent> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _TemplateRef_1_5:any;
  _NgIf_1_6:import13.NgIf;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import13.NgIf;
  _text_4:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaComponent0,renderType_ArenaComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'    ',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import14.TemplateRef_(this._appEl_1,viewFactory_ArenaComponent1);
    this._NgIf_1_6 = new import13.NgIf(this._appEl_1.vcRef,this._TemplateRef_1_5);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n    ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_3 = new import2.AppElement(3,(null as any),this,this._anchor_3);
    this._TemplateRef_3_5 = new import14.TemplateRef_(this._appEl_3,viewFactory_ArenaComponent2);
    this._NgIf_3_6 = new import13.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._anchor_1,
      this._text_2,
      this._anchor_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import13.NgIf) && (1 === requestNodeIndex))) { return this._NgIf_1_6; }
    if (((token === import14.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import13.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = (this.context.isUserPlaying == false);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_1_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.context.isUserPlaying == true);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_3_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ArenaComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ArenaComponent> {
  if ((renderType_ArenaComponent === (null as any))) { (renderType_ArenaComponent = viewUtils.createRenderComponentType('C:/Users/alex/WebstormProjects/footbalQuiz/assets/app/MainApp/arena/arena.component.html',0,import11.ViewEncapsulation.None,styles_ArenaComponent,{})); }
  return new _View_ArenaComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ArenaComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _ArenaHeaderComponent_2_4:import15.ArenaHeaderComponent;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _OpponentComponentFind_6_4:import16.OpponentComponentFind;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _GameListcomponent_11_4:import17.GameListcomponent;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaComponent1,renderType_ArenaComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'arena-header',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_ArenaHeaderComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._ArenaHeaderComponent_2_4 = new import15.ArenaHeaderComponent(this.parentInjector.get(import10.SocketService));
    this._appEl_2.initComponent(this._ArenaHeaderComponent_2_4,[],compView_2);
    compView_2.create(this._ArenaHeaderComponent_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-md-5 col-lg-5 col-sm-5');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'opponent-find',(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import19.viewFactory_OpponentComponentFind0(this.viewUtils,this.injector(6),this._appEl_6);
    this._OpponentComponentFind_6_4 = new import16.OpponentComponentFind(this.parentInjector.get(import20.OpponentFindService),this.parentInjector.get(import10.SocketService));
    this._appEl_6.initComponent(this._OpponentComponentFind_6_4,[],compView_6);
    compView_6.create(this._OpponentComponentFind_6_4,[],(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-md-7');
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'game-list',(null as any));
    this._appEl_11 = new import2.AppElement(11,9,this,this._el_11);
    var compView_11:any = import21.viewFactory_GameListcomponent0(this.viewUtils,this.injector(11),this._appEl_11);
    this._GameListcomponent_11_4 = new import17.GameListcomponent(this.parentInjector.get(import10.SocketService),this.parentInjector.get(import8.AuthService));
    this._appEl_11.initComponent(this._GameListcomponent_11_4,[],compView_11);
    compView_11.create(this._GameListcomponent_11_4,[],(null as any));
    this._text_12 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.ArenaHeaderComponent) && (2 === requestNodeIndex))) { return this._ArenaHeaderComponent_2_4; }
    if (((token === import16.OpponentComponentFind) && (6 === requestNodeIndex))) { return this._OpponentComponentFind_6_4; }
    if (((token === import17.GameListcomponent) && (11 === requestNodeIndex))) { return this._GameListcomponent_11_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.userName;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ArenaHeaderComponent_2_4.username = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.stats;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ArenaHeaderComponent_2_4.stats = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._OpponentComponentFind_6_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._GameListcomponent_11_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._GameListcomponent_11_4.ngOnDestroy();
  }
}
function viewFactory_ArenaComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArenaComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ArenaComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ArenaPlayingComponent_4_4:import22.ArenaPlayingComponent;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaComponent2,renderType_ArenaComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-md-5');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'arena-playing',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import23.viewFactory_ArenaPlayingComponent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ArenaPlayingComponent_4_4 = new import22.ArenaPlayingComponent(this.parentInjector.get(import24.QuestionAnswerServices),this.parentInjector.get(import8.AuthService),this.parentInjector.get(import25.ArenaServices),this.parentInjector.get(import10.SocketService),this.parentInjector.get(import9.GameListServices));
    this._appEl_4.initComponent(this._ArenaPlayingComponent_4_4,[],compView_4);
    compView_4.create(this._ArenaPlayingComponent_4_4,[],(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.ArenaPlayingComponent) && (4 === requestNodeIndex))) { return this._ArenaPlayingComponent_4_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.arenas;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ArenaPlayingComponent_4_4.arenas = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ArenaPlayingComponent_4_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._ArenaPlayingComponent_4_4.ngOnDestroy();
  }
}
function viewFactory_ArenaComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArenaComponent2(viewUtils,parentInjector,declarationEl);
}