/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './arena-header.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../socketHanding/socket.service';
import * as import9 from '../../auth/auth.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
var renderType_ArenaHeaderComponent_Host:import0.RenderComponentType = (null as any);
class _View_ArenaHeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ArenaHeaderComponent_0_4:import3.ArenaHeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaHeaderComponent_Host0,renderType_ArenaHeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('arena-header',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ArenaHeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ArenaHeaderComponent_0_4 = new import3.ArenaHeaderComponent(this.parentInjector.get(import8.SocketService),this.parentInjector.get(import9.AuthService));
    this._appEl_0.initComponent(this._ArenaHeaderComponent_0_4,[],compView_0);
    compView_0.create(this._ArenaHeaderComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ArenaHeaderComponent) && (0 === requestNodeIndex))) { return this._ArenaHeaderComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ArenaHeaderComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ArenaHeaderComponent_Host === (null as any))) { (renderType_ArenaHeaderComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_ArenaHeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ArenaHeaderComponentNgFactory:import11.ComponentFactory<import3.ArenaHeaderComponent> = new import11.ComponentFactory<import3.ArenaHeaderComponent>('arena-header',viewFactory_ArenaHeaderComponent_Host0,import3.ArenaHeaderComponent);
const styles_ArenaHeaderComponent:any[] = [];
var renderType_ArenaHeaderComponent:import0.RenderComponentType = (null as any);
class _View_ArenaHeaderComponent0 extends import1.AppView<import3.ArenaHeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaHeaderComponent0,renderType_ArenaHeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','navbar navbar-inverse');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container-fluid');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','navbar-header');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'a',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','navbar-brand');
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','nav navbar-nav');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'li',(null as any));
    this._el_13 = this.renderer.createElement(this._el_12,'a',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','navbar-brand');
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_12,' ',(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_10,'li',(null as any));
    this._el_18 = this.renderer.createElement(this._el_17,'a',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','navbar-brand');
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_17,' ',(null as any));
    this._text_21 = this.renderer.createText(this._el_10,'        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_2,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','nav navbar-nav navbar-right');
    this._el_24 = this.renderer.createElement(this._el_23,'li',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','dropdown');
    this._el_25 = this.renderer.createElement(this._el_24,'a',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','dropdown-toggle glyphicon glyphicon-wrench');
    this.renderer.setElementAttribute(this._el_25,'data-toggle','dropdown');
    this._text_26 = this.renderer.createText(this._el_25,'settings ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'span',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','caret');
    this._text_28 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_24,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','dropdown-menu');
    this._text_30 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'li',(null as any));
    this._el_32 = this.renderer.createElement(this._el_31,'a',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Logout',(null as any));
    this._text_34 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_29,'li',(null as any));
    this._el_36 = this.renderer.createElement(this._el_35,'a',(null as any));
    this.renderer.setElementAttribute(this._el_36,'href','#');
    this._text_37 = this.renderer.createText(this._el_36,'Options',(null as any));
    this._text_38 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._text_39 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_40 = this.renderer.createText(this._el_23,'\n\n\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_43 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.username,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,' Level: ',((this.context.stats == (null as any))? (null as any): this.context.stats.level),'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_14,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'CurrentExp : ',((this.context.stats == (null as any))? (null as any): this.context.stats.currentExp),'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_19,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.logout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ArenaHeaderComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ArenaHeaderComponent> {
  if ((renderType_ArenaHeaderComponent === (null as any))) { (renderType_ArenaHeaderComponent = viewUtils.createRenderComponentType('C:/Users/alex/WebstormProjects/footbalQuiz/assets/app/MainApp/arena/arena-header.component.html',0,import10.ViewEncapsulation.None,styles_ArenaHeaderComponent,{})); }
  return new _View_ArenaHeaderComponent0(viewUtils,parentInjector,declarationEl);
}