/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './game-item.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../auth/auth.service';
import * as import9 from './game-list.services';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/common/src/directives/ng_style';
import * as import16 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from 'ng2-bs3-modal/components/modal';
import * as import19 from 'ng2-bs3-modal/components/modal-header';
import * as import20 from 'ng2-bs3-modal/components/modal-body';
import * as import21 from 'ng2-bs3-modal/components/modal-footer';
import * as import22 from '../../../../node_modules/ng2-bs3-modal/components/modal.ngfactory';
import * as import23 from '../../../../node_modules/ng2-bs3-modal/components/modal-header.ngfactory';
import * as import24 from '../../../../node_modules/ng2-bs3-modal/components/modal-body.ngfactory';
import * as import25 from '../../../../node_modules/ng2-bs3-modal/components/modal-footer.ngfactory';
var renderType_GameItemComponent_Host:import0.RenderComponentType = (null as any);
class _View_GameItemComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _GameItemComponent_0_4:import3.GameItemComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent_Host0,renderType_GameItemComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('game-item',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_GameItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._GameItemComponent_0_4 = new import3.GameItemComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.GameListServices));
    this._appEl_0.initComponent(this._GameItemComponent_0_4,[],compView_0);
    compView_0.create(this._GameItemComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.GameItemComponent) && (0 === requestNodeIndex))) { return this._GameItemComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._GameItemComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._GameItemComponent_0_4.ngOnDestroy();
  }
}
function viewFactory_GameItemComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_GameItemComponent_Host === (null as any))) { (renderType_GameItemComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_GameItemComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const GameItemComponentNgFactory:import11.ComponentFactory<import3.GameItemComponent> = new import11.ComponentFactory<import3.GameItemComponent>('game-item',viewFactory_GameItemComponent_Host0,import3.GameItemComponent);
const styles_GameItemComponent:any[] = ['.author[_ngcontent-%COMP%]{\n        display:inline-block;\n        font-style: italic;\n        font-size: 12px;\n        width: 80%;\n        }\n        .config[_ngcontent-%COMP%]{\n        display: inline-block;\n        text-align: right;\n        font-size: 12px;\n        width: 19%;\n        }\n        a.disabled[_ngcontent-%COMP%]{\n            pointer-events: none;\n            cursor: default;\n        }'];
var renderType_GameItemComponent:import0.RenderComponentType = (null as any);
class _View_GameItemComponent0 extends import1.AppView<import3.GameItemComponent> {
  _viewQuery_myModal_0:import12.QueryList<any>;
  _text_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import13.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import13.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent0,renderType_GameItemComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_myModal_0 = new import12.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import14.TemplateRef_(this._appEl_2,viewFactory_GameItemComponent1);
    this._NgIf_2_6 = new import13.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_4 = new import2.AppElement(4,(null as any),this,this._anchor_4);
    this._TemplateRef_4_5 = new import14.TemplateRef_(this._appEl_4,viewFactory_GameItemComponent4);
    this._NgIf_4_6 = new import13.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(parentRenderNode,'\n\n\n \n\n\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import13.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import14.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import13.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = (((this.context.arena.userId == this.context.userId) && (this.context.arena.user_played == false)) || ((this.context.arena.inviteId == this.context.userId) && (this.context.arena.invite_played == false)));
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (((this.context.arena.userId == this.context.userId) && (this.context.arena.user_played == true)) || ((this.context.arena.inviteId == this.context.userId) && (this.context.arena.invite_played == true)));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._viewQuery_myModal_0.dirty) {
        this._viewQuery_myModal_0.reset([this._appEl_4.mapNestedViews(_View_GameItemComponent4,(nestedView:_View_GameItemComponent4):any => {
          return [nestedView._ModalComponent_21_4];
      })]);
      this.context.modal = this._viewQuery_myModal_0.first;
    } }
  }
}
export function viewFactory_GameItemComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.GameItemComponent> {
  if ((renderType_GameItemComponent === (null as any))) { (renderType_GameItemComponent = viewUtils.createRenderComponentType('C:/Users/alex/WebstormProjects/footbalQuiz/assets/app/MainApp/game-list/game-item.component.ts class GameItemComponent - inline template',0,import10.ViewEncapsulation.Emulated,styles_GameItemComponent,{})); }
  return new _View_GameItemComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_GameItemComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import13.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import13.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent1,renderType_GameItemComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import14.TemplateRef_(this._appEl_2,viewFactory_GameItemComponent2);
    this._NgIf_2_6 = new import13.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import14.TemplateRef_(this._appEl_4,viewFactory_GameItemComponent3);
    this._NgIf_4_6 = new import13.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import13.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import14.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import13.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = (this.parent.context.arena.userId == this.parent.context.userId);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.context.arena.inviteId == this.parent.context.userId);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_GameItemComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GameItemComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_GameItemComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _NgStyle_5_3:import15.NgStyle;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent2,renderType_GameItemComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','list-group-item clearfix');
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'article',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','panel panel-default');
    this._NgStyle_5_3 = new import15.NgStyle(this.parent.parentInjector.get(import16.KeyValueDiffers),new import17.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','panel-body');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'footer',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','panel-footer');
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','author');
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {backgroundColor: p0};
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.NgStyle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._NgStyle_5_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this._map_0(this.parent.parent.context.color);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgStyle_5_3.ngStyle = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgStyle_5_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'\n        ',((this.parent.parent.context.arena == (null as any))? (null as any): this.parent.parent.context.arena.lastName),' \n    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'\n            ',((this.parent.parent.context.arena == (null as any))? (null as any): this.parent.parent.context.arena.status_accept),'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_13,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.sendArenaInfo(this.parent.parent.context.arena)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_GameItemComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GameItemComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_GameItemComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _NgStyle_5_3:import15.NgStyle;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent3,renderType_GameItemComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','list-group-item clearfix');
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'article',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','panel panel-default');
    this._NgStyle_5_3 = new import15.NgStyle(this.parent.parentInjector.get(import16.KeyValueDiffers),new import17.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','panel-body');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'footer',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','panel-footer');
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','author');
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {backgroundColor: p0};
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.NgStyle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._NgStyle_5_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this._map_0(this.parent.parent.context.color);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgStyle_5_3.ngStyle = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgStyle_5_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'\n        ',((this.parent.parent.context.arena == (null as any))? (null as any): this.parent.parent.context.arena.lastName),' \n    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'\n            ',((this.parent.parent.context.arena == (null as any))? (null as any): this.parent.parent.context.arena.status_accept),'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_13,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.sendArenaInfo(this.parent.parent.context.arena)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_GameItemComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GameItemComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_GameItemComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _NgStyle_5_3:import15.NgStyle;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import13.NgIf;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _ModalComponent_21_4:import18.ModalComponent;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _ModalHeaderComponent_23_4:import19.ModalHeaderComponent;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _ModalBodyComponent_29_4:import20.ModalBodyComponent;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import13.NgIf;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import13.NgIf;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _ModalFooterComponent_36_4:import21.ModalFooterComponent;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_0:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent4,renderType_GameItemComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','list-group-item clearfix');
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'article',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','panel panel-default');
    this._NgStyle_5_3 = new import15.NgStyle(this.parentInjector.get(import16.KeyValueDiffers),new import17.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','panel-body');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'footer',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','panel-footer');
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','author');
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_19 = new import2.AppElement(19,0,this,this._anchor_19);
    this._TemplateRef_19_5 = new import14.TemplateRef_(this._appEl_19,viewFactory_GameItemComponent5);
    this._NgIf_19_6 = new import13.NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_0,'modal',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','modal');
    this.renderer.setElementAttribute(this._el_21,'role','dialog');
    this.renderer.setElementAttribute(this._el_21,'tabindex','-1');
    this._appEl_21 = new import2.AppElement(21,0,this,this._el_21);
    var compView_21:any = import22.viewFactory_ModalComponent0(this.viewUtils,this.injector(21),this._appEl_21);
    this._ModalComponent_21_4 = new import18.ModalComponent(new import17.ElementRef(this._el_21));
    this._appEl_21.initComponent(this._ModalComponent_21_4,[],compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'modal-header',(null as any));
    this._appEl_23 = new import2.AppElement(23,21,this,this._el_23);
    var compView_23:any = import23.viewFactory_ModalHeaderComponent0(this.viewUtils,this.injector(23),this._appEl_23);
    this._ModalHeaderComponent_23_4 = new import19.ModalHeaderComponent(this._ModalComponent_21_4);
    this._appEl_23.initComponent(this._ModalHeaderComponent_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'h4',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','modal-title');
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_23.create(this._ModalHeaderComponent_23_4,[[].concat([
        this._text_24,
        this._el_25,
        this._text_27
      ]
    )],(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'modal-body',(null as any));
    this._appEl_29 = new import2.AppElement(29,21,this,this._el_29);
    var compView_29:any = import24.viewFactory_ModalBodyComponent0(this.viewUtils,this.injector(29),this._appEl_29);
    this._ModalBodyComponent_29_4 = new import20.ModalBodyComponent();
    this._appEl_29.initComponent(this._ModalBodyComponent_29_4,[],compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_31 = new import2.AppElement(31,29,this,this._anchor_31);
    this._TemplateRef_31_5 = new import14.TemplateRef_(this._appEl_31,viewFactory_GameItemComponent6);
    this._NgIf_31_6 = new import13.NgIf(this._appEl_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText((null as any),'    \n            ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_33 = new import2.AppElement(33,29,this,this._anchor_33);
    this._TemplateRef_33_5 = new import14.TemplateRef_(this._appEl_33,viewFactory_GameItemComponent7);
    this._NgIf_33_6 = new import13.NgIf(this._appEl_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_29.create(this._ModalBodyComponent_29_4,[[].concat([
        this._text_30,
        this._appEl_31,
        this._text_32,
        this._appEl_33,
        this._text_34
      ]
    )],(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'modal-footer',(null as any));
    this._appEl_36 = new import2.AppElement(36,21,this,this._el_36);
    var compView_36:any = import25.viewFactory_ModalFooterComponent0(this.viewUtils,this.injector(36),this._appEl_36);
    this._ModalFooterComponent_36_4 = new import21.ModalFooterComponent(this._ModalComponent_21_4);
    this._appEl_36.initComponent(this._ModalFooterComponent_36_4,[],compView_36);
    compView_36.create(this._ModalFooterComponent_36_4,[[]],(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_21.create(this._ModalComponent_21_4,[[].concat([
        this._text_22,
        this._el_23,
        this._text_28,
        this._el_29,
        this._text_35,
        this._el_36,
        this._text_37
      ]
    )],(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {backgroundColor: p0};
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.NgStyle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._NgStyle_5_3; }
    if (((token === import14.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import13.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6; }
    if (((token === import19.ModalHeaderComponent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ModalHeaderComponent_23_4; }
    if (((token === import14.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import13.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6; }
    if (((token === import14.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import13.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6; }
    if (((token === import20.ModalBodyComponent) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ModalBodyComponent_29_4; }
    if (((token === import21.ModalFooterComponent) && (36 === requestNodeIndex))) { return this._ModalFooterComponent_36_4; }
    if (((token === import18.ModalComponent) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ModalComponent_21_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this._map_0(this.parent.context.color);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgStyle_5_3.ngStyle = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgStyle_5_3.ngDoCheck(); }
    const currVal_4:any = ((this.parent.context.arena.user_played == true) && (this.parent.context.arena.invite_played == true));
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_19_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'static';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._ModalComponent_21_4.backdrop = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = false;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._ModalComponent_21_4.keyboard = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_10:any = false;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._ModalHeaderComponent_23_4.showClose = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_12:any = (((this.parent.context.playerResult == (null as any))? (null as any): this.parent.context.playerResult.winnerUserId) == this.parent.context.userId);
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_31_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = (((this.parent.context.playerResult == (null as any))? (null as any): this.parent.context.playerResult.loserUserId) == this.parent.context.userId);
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgIf_33_6.ngIf = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = true;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._ModalFooterComponent_36_4.showDefaultButtons = currVal_14;
      this._expr_14 = currVal_14;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = true;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_3,'disabled',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = import4.interpolate(1,'\n        ',((this.parent.context.arena == (null as any))? (null as any): this.parent.context.arena.lastName),' \n    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'\n            ',((this.parent.context.arena == (null as any))? (null as any): this.parent.context.arena.status_accept),'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_13,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = this._ModalComponent_21_4.fadeClass;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_21,'fade',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._ModalComponent_21_4.dataKeyboardAttr;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementAttribute(this._el_21,'data-keyboard',((currVal_8 == (null as any))? (null as any): currVal_8.toString()));
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._ModalComponent_21_4.dataBackdropAttr;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementAttribute(this._el_21,'data-backdrop',((currVal_9 == (null as any))? (null as any): currVal_9.toString()));
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = import4.interpolate(1,'You played against ',this.parent.context.arena.lastName,'');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_26,currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_GameItemComponent0>this.parent)._viewQuery_myModal_0.setDirty();
  }
  destroyInternal():void {
    this._ModalComponent_21_4.ngOnDestroy();
  }
}
function viewFactory_GameItemComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GameItemComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_GameItemComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent5,renderType_GameItemComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_2,'type','button');
    this._text_3 = this.renderer.createText(this._el_2,'Show results',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.showResult(this.parent.parent.context.arena.arenaId)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_GameItemComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GameItemComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_GameItemComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent6,renderType_GameItemComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Congratulation You Won!!!!',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_GameItemComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GameItemComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_GameItemComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_GameItemComponent7,renderType_GameItemComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Sorry you lost....!!!!',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_GameItemComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GameItemComponent7(viewUtils,parentInjector,declarationEl);
}