/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './arena-playing.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './questionServices/questionAnswer.service';
import * as import9 from '../auth/auth.service';
import * as import10 from './questionServices/arena.service';
import * as import11 from '../MainApp/socketHanding/socket.service';
import * as import12 from '../MainApp/game-list/game-list.services';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from 'ng2-bs3-modal/components/modal';
import * as import18 from 'ng2-bs3-modal/components/modal-header';
import * as import19 from 'ng2-bs3-modal/components/modal-body';
import * as import20 from 'ng2-bs3-modal/components/modal-footer';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '../../../node_modules/ng2-bs3-modal/components/modal.ngfactory';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '../../../node_modules/ng2-bs3-modal/components/modal-header.ngfactory';
import * as import25 from '../../../node_modules/ng2-bs3-modal/components/modal-body.ngfactory';
import * as import26 from '../../../node_modules/ng2-bs3-modal/components/modal-footer.ngfactory';
import * as import27 from '@angular/common/src/directives/ng_for';
import * as import28 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import29 from '@angular/core/src/security';
var renderType_ArenaPlayingComponent_Host:import0.RenderComponentType = (null as any);
class _View_ArenaPlayingComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ArenaPlayingComponent_0_4:import3.ArenaPlayingComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaPlayingComponent_Host0,renderType_ArenaPlayingComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('arena-playing',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ArenaPlayingComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ArenaPlayingComponent_0_4 = new import3.ArenaPlayingComponent(this.parentInjector.get(import8.QuestionAnswerServices),this.parentInjector.get(import9.AuthService),this.parentInjector.get(import10.ArenaServices),this.parentInjector.get(import11.SocketService),this.parentInjector.get(import12.GameListServices),this.renderer);
    this._appEl_0.initComponent(this._ArenaPlayingComponent_0_4,[],compView_0);
    compView_0.create(this._ArenaPlayingComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ArenaPlayingComponent) && (0 === requestNodeIndex))) { return this._ArenaPlayingComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ArenaPlayingComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._ArenaPlayingComponent_0_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._ArenaPlayingComponent_0_4.ngOnDestroy();
  }
}
function viewFactory_ArenaPlayingComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ArenaPlayingComponent_Host === (null as any))) { (renderType_ArenaPlayingComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_ArenaPlayingComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ArenaPlayingComponentNgFactory:import14.ComponentFactory<import3.ArenaPlayingComponent> = new import14.ComponentFactory<import3.ArenaPlayingComponent>('arena-playing',viewFactory_ArenaPlayingComponent_Host0,import3.ArenaPlayingComponent);
const styles_ArenaPlayingComponent:any[] = [];
var renderType_ArenaPlayingComponent:import0.RenderComponentType = (null as any);
class _View_ArenaPlayingComponent0 extends import1.AppView<import3.ArenaPlayingComponent> {
  _viewQuery_myModal_0:import15.QueryList<any>;
  _viewQuery_button1_1:import15.QueryList<any>;
  _viewQuery_button2_2:import15.QueryList<any>;
  _viewQuery_button3_3:import15.QueryList<any>;
  _viewQuery_button4_4:import15.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import16.NgIf;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ModalComponent_5_4:import17.ModalComponent;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _ModalHeaderComponent_7_4:import18.ModalHeaderComponent;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _ModalBodyComponent_13_4:import19.ModalBodyComponent;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _ModalFooterComponent_16_4:import20.ModalFooterComponent;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaPlayingComponent0,renderType_ArenaPlayingComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_myModal_0 = new import15.QueryList<any>();
    this._viewQuery_button1_1 = new import15.QueryList<any>();
    this._viewQuery_button2_2 = new import15.QueryList<any>();
    this._viewQuery_button3_3 = new import15.QueryList<any>();
    this._viewQuery_button4_4 = new import15.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'h3',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_3 = new import2.AppElement(3,(null as any),this,this._anchor_3);
    this._TemplateRef_3_5 = new import21.TemplateRef_(this._appEl_3,viewFactory_ArenaPlayingComponent1);
    this._NgIf_3_6 = new import16.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_5 = this.renderer.createElement(parentRenderNode,'modal',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','modal');
    this.renderer.setElementAttribute(this._el_5,'role','dialog');
    this.renderer.setElementAttribute(this._el_5,'tabindex','-1');
    this._appEl_5 = new import2.AppElement(5,(null as any),this,this._el_5);
    var compView_5:any = import22.viewFactory_ModalComponent0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ModalComponent_5_4 = new import17.ModalComponent(new import23.ElementRef(this._el_5));
    this._appEl_5.initComponent(this._ModalComponent_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'modal-header',(null as any));
    this._appEl_7 = new import2.AppElement(7,5,this,this._el_7);
    var compView_7:any = import24.viewFactory_ModalHeaderComponent0(this.viewUtils,this.injector(7),this._appEl_7);
    this._ModalHeaderComponent_7_4 = new import18.ModalHeaderComponent(this._ModalComponent_5_4);
    this._appEl_7.initComponent(this._ModalHeaderComponent_7_4,[],compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h4',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','modal-title');
    this._text_10 = this.renderer.createText(this._el_9,'I\'m a modal!',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_7.create(this._ModalHeaderComponent_7_4,[[].concat([
        this._text_8,
        this._el_9,
        this._text_11
      ]
    )],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'modal-body',(null as any));
    this._appEl_13 = new import2.AppElement(13,5,this,this._el_13);
    var compView_13:any = import25.viewFactory_ModalBodyComponent0(this.viewUtils,this.injector(13),this._appEl_13);
    this._ModalBodyComponent_13_4 = new import19.ModalBodyComponent();
    this._appEl_13.initComponent(this._ModalBodyComponent_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n        Sorry,you lost! You answered correct :\n    ',(null as any));
    compView_13.create(this._ModalBodyComponent_13_4,[[].concat([this._text_14])],(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'modal-footer',(null as any));
    this._appEl_16 = new import2.AppElement(16,5,this,this._el_16);
    var compView_16:any = import26.viewFactory_ModalFooterComponent0(this.viewUtils,this.injector(16),this._appEl_16);
    this._ModalFooterComponent_16_4 = new import20.ModalFooterComponent(this._ModalComponent_5_4);
    this._appEl_16.initComponent(this._ModalFooterComponent_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_18,'type','button');
    this._text_19 = this.renderer.createText(this._el_18,'Ok',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_16.create(this._ModalFooterComponent_16_4,[[].concat([
        this._text_17,
        this._el_18,
        this._text_20
      ]
    )],(null as any));
      compView_5.create(this._ModalComponent_5_4,[[].concat([
        this._text_6,
        this._el_7,
        this._text_12,
        this._el_13,
        this._text_15,
        this._el_16
      ]
    )],(null as any));
    this._text_21 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this._viewQuery_myModal_0.reset([this._ModalComponent_5_4]);
    this.context.modal = this._viewQuery_myModal_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import16.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    if (((token === import18.ModalHeaderComponent) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ModalHeaderComponent_7_4; }
    if (((token === import19.ModalBodyComponent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ModalBodyComponent_13_4; }
    if (((token === import20.ModalFooterComponent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ModalFooterComponent_16_4; }
    if (((token === import17.ModalComponent) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ModalComponent_5_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:boolean = !this.context.isLost;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_3_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = 'static';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._ModalComponent_5_4.backdrop = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = false;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._ModalComponent_5_4.keyboard = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = false;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._ModalHeaderComponent_7_4.showClose = currVal_7;
      this._expr_7 = currVal_7;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.userName,' you are playing....');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = this._ModalComponent_5_4.fadeClass;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_5,'fade',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._ModalComponent_5_4.dataKeyboardAttr;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementAttribute(this._el_5,'data-keyboard',((currVal_5 == (null as any))? (null as any): currVal_5.toString()));
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._ModalComponent_5_4.dataBackdropAttr;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementAttribute(this._el_5,'data-backdrop',((currVal_6 == (null as any))? (null as any): currVal_6.toString()));
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._viewQuery_button1_1.dirty) {
          this._viewQuery_button1_1.reset([this._appEl_3.mapNestedViews(_View_ArenaPlayingComponent1,(nestedView:_View_ArenaPlayingComponent1):any => {
              return [nestedView._appEl_11.mapNestedViews(_View_ArenaPlayingComponent2,(nestedView:_View_ArenaPlayingComponent2):any => {
                  return [nestedView._appEl_2.mapNestedViews(_View_ArenaPlayingComponent3,(nestedView:_View_ArenaPlayingComponent3):any => {
                    return [new import23.ElementRef(nestedView._el_18)];
                })];
            })];
        })]);
        this.context.el = this._viewQuery_button1_1.first;
      }
      if (this._viewQuery_button2_2.dirty) {
          this._viewQuery_button2_2.reset([this._appEl_3.mapNestedViews(_View_ArenaPlayingComponent1,(nestedView:_View_ArenaPlayingComponent1):any => {
              return [nestedView._appEl_11.mapNestedViews(_View_ArenaPlayingComponent2,(nestedView:_View_ArenaPlayingComponent2):any => {
                  return [nestedView._appEl_2.mapNestedViews(_View_ArenaPlayingComponent3,(nestedView:_View_ArenaPlayingComponent3):any => {
                    return [new import23.ElementRef(nestedView._el_24)];
                })];
            })];
        })]);
        this.context.el1 = this._viewQuery_button2_2.first;
      }
      if (this._viewQuery_button3_3.dirty) {
          this._viewQuery_button3_3.reset([this._appEl_3.mapNestedViews(_View_ArenaPlayingComponent1,(nestedView:_View_ArenaPlayingComponent1):any => {
              return [nestedView._appEl_11.mapNestedViews(_View_ArenaPlayingComponent2,(nestedView:_View_ArenaPlayingComponent2):any => {
                  return [nestedView._appEl_2.mapNestedViews(_View_ArenaPlayingComponent3,(nestedView:_View_ArenaPlayingComponent3):any => {
                    return [new import23.ElementRef(nestedView._el_37)];
                })];
            })];
        })]);
        this.context.el2 = this._viewQuery_button3_3.first;
      }
      if (this._viewQuery_button4_4.dirty) {
          this._viewQuery_button4_4.reset([this._appEl_3.mapNestedViews(_View_ArenaPlayingComponent1,(nestedView:_View_ArenaPlayingComponent1):any => {
              return [nestedView._appEl_11.mapNestedViews(_View_ArenaPlayingComponent2,(nestedView:_View_ArenaPlayingComponent2):any => {
                  return [nestedView._appEl_2.mapNestedViews(_View_ArenaPlayingComponent3,(nestedView:_View_ArenaPlayingComponent3):any => {
                    return [new import23.ElementRef(nestedView._el_43)];
                })];
            })];
        })]);
        this.context.el3 = this._viewQuery_button4_4.first;
      }
    }
  }
  destroyInternal():void {
    this._ModalComponent_5_4.ngOnDestroy();
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.close()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ArenaPlayingComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ArenaPlayingComponent> {
  if ((renderType_ArenaPlayingComponent === (null as any))) { (renderType_ArenaPlayingComponent = viewUtils.createRenderComponentType('C:/Users/alex/WebstormProjects/footbalQuiz/assets/app/questions/arena-playing.component.html',0,import13.ViewEncapsulation.None,styles_ArenaPlayingComponent,{})); }
  return new _View_ArenaPlayingComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ArenaPlayingComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgFor_11_6:import27.NgFor;
  _text_12:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaPlayingComponent1,renderType_ArenaPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','progress');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'aria-valuemax','30');
    this.renderer.setElementAttribute(this._el_6,'aria-valuemin','0');
    this.renderer.setElementAttribute(this._el_6,'class','progress-bar');
    this.renderer.setElementAttribute(this._el_6,'role','progressbar');
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_11 = new import2.AppElement(11,0,this,this._anchor_11);
    this._TemplateRef_11_5 = new import21.TemplateRef_(this._appEl_11,viewFactory_ArenaPlayingComponent2);
    this._NgFor_11_6 = new import27.NgFor(this._appEl_11.vcRef,this._TemplateRef_11_5,this.parentInjector.get(import28.IterableDiffers),this.parent.ref);
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import27.NgFor) && (11 === requestNodeIndex))) { return this._NgFor_11_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = this.parent.context.arenaQuestions;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_11_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_11_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_11_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.ticks;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementAttribute(this._el_6,'aria-valuenow',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.context.ticks * 3.4);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_6,'width',((this.viewUtils.sanitizer.sanitize(import29.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import29.SecurityContext.STYLE,currVal_1).toString() + '%')));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ArenaPlayingComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArenaPlayingComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ArenaPlayingComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import16.NgIf;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaPlayingComponent2,renderType_ArenaPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import21.TemplateRef_(this._appEl_2,viewFactory_ArenaPlayingComponent3);
    this._NgIf_2_6 = new import16.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = (this.context.index == this.parent.parent.context.index);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ArenaPlayingComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArenaPlayingComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ArenaPlayingComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaPlayingComponent3,renderType_ArenaPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-xs-12');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-xs-12 ');
    this._text_5 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_6,'onload','');
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_0,'br',(null as any));
    this._el_12 = this.renderer.createElement(this._el_0,'br',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n\n            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','row');
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','col-xs-1 col-sm-offset-4');
    this._text_17 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','btn btn-success');
    this.renderer.setElementAttribute(this._el_18,'type','submit');
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','col-xs-1 col-sm-offset-1');
    this._text_23 = this.renderer.createText(this._el_22,'\n                    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','btn btn-success');
    this.renderer.setElementAttribute(this._el_24,'type','submit');
    this._text_25 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_0,'br',(null as any));
    this._text_30 = this.renderer.createText(this._el_0,' ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_0,'br',(null as any));
    this._text_32 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','row');
    this._text_34 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','col-xs-1 col-sm-offset-4');
    this._text_36 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'button',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','btn btn-success');
    this.renderer.setElementAttribute(this._el_37,'type','submit');
    this._text_38 = this.renderer.createText(this._el_37,'',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','col-xs-1 col-sm-offset-1');
    this._text_42 = this.renderer.createText(this._el_41,'\n                    ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'button',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','btn btn-success');
    this.renderer.setElementAttribute(this._el_43,'type','submit');
    this._text_44 = this.renderer.createText(this._el_43,'',(null as any));
    this._text_45 = this.renderer.createText(this._el_41,'\n                ',(null as any));
    this._text_46 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._text_47 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_43,'click',this.eventHandler(this._handle_click_43_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n                        ',this.parent.context.$implicit.question,'\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = import4.interpolate(1,'',this.parent.context.$implicit.optiona,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_19,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = import4.interpolate(1,'',this.parent.context.$implicit.optionb,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_25,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = import4.interpolate(1,'',this.parent.context.$implicit.optionc,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_38,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_8:any = import4.interpolate(1,'',this.parent.context.$implicit.optiond,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_44,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_ArenaPlayingComponent0>this.parent.parent.parent)._viewQuery_button1_1.setDirty();
    (<_View_ArenaPlayingComponent0>this.parent.parent.parent)._viewQuery_button2_2.setDirty();
    (<_View_ArenaPlayingComponent0>this.parent.parent.parent)._viewQuery_button3_3.setDirty();
    (<_View_ArenaPlayingComponent0>this.parent.parent.parent)._viewQuery_button4_4.setDirty();
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.onChooseQuestion(this.parent.context.$implicit,this.parent.context.$implicit.optiona,1)) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.onChooseQuestion(this.parent.context.$implicit,this.parent.context.$implicit.optionb,2)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.onChooseQuestion(this.parent.context.$implicit,this.parent.context.$implicit.optionc,3)) !== false);
    return (true && pd_0);
  }
  private _handle_click_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.onChooseQuestion(this.parent.context.$implicit,this.parent.context.$implicit.optiond,4)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ArenaPlayingComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArenaPlayingComponent3(viewUtils,parentInjector,declarationEl);
}